In [19]:
"""
Creating same plots using giotto's mapper.
"""

# Data handling
import numpy as np
import pandas as pd

# Data vizualization
from gtda.plotting import plot_point_cloud

from gtda.mapper import (
    CubicalCover,
    make_mapper_pipeline,
    Projection,
    plot_static_mapper_graph,
    plot_interactive_mapper_graph,
    MapperInteractivePlotter
)

from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
from sklearn.preprocessing import normalize
from gtda.mapper.cluster import FirstSimpleGap


from main import GenerateVectors

from sklearn import datasets


DengueDataCSV = '../data/strict-data/2010DengueData.csv'
DengueDataCSV2 = '../data/created-data/north_increase/factor/north_factor=2.csv'

DengueDataFrame = pd.read_csv(DengueDataCSV2)

VectorList, LabelsList = GenerateVectors(DengueDataFrame)
NormalizedVectorList = normalize(VectorList, norm='l2', axis=0)
print(NormalizedVectorList)



# data, _ = datasets.make_circles(n_samples=5000, noise=0.05, factor=0.3, random_state=42)
# print(data)
# plot_point_cloud(np.array(VectorList))

filter_func = Projection(columns=[0,1,2,3])
cover = CubicalCover(n_intervals=10, overlap_frac=0.15)
clusterer = DBSCAN()

n_jobs = 1

pipe = make_mapper_pipeline(
    filter_func=filter_func,
    cover=cover,
    clusterer=clusterer,
    verbose=False,
    n_jobs=n_jobs
)


fig = plot_static_mapper_graph(pipe, NormalizedVectorList, layout_dim=3)
fig.show(config={'scollZoom': True})


[[-1.49197980e-02 -1.49588701e-02  4.63785928e-06  4.74730850e-04]
 [-1.49197980e-02 -1.49588701e-02  9.56558477e-06  9.49461701e-04]
 [-1.49197980e-02 -1.49588701e-02  1.47831765e-05  1.42419255e-03]
 ...
 [-1.46060201e-02 -1.48872043e-02  8.62351960e-04  2.37365425e-02]
 [-1.46060201e-02 -1.48872043e-02  8.86990587e-04  2.42112734e-02]
 [-1.46060201e-02 -1.48872043e-02  9.11919081e-04  2.46860042e-02]]


/home/franreno/.local/lib/python3.8/site-packages/plotly/offline/offline.py:157: UserWarning:


Unrecognized config options supplied: ['scollZoom']

